from pathlib import Path
p=Path(__file__).resolve().parent
nav=[('index.html','About Me'),('projects.html','Projects'),('references.html','Reference Hub'),('certifications.html','Certifications')]
def page(file,title,body):
 n=''.join(f'<a href="/{f}" '+('aria-current="page"' if f==file else '')+f'>{t}</a>' for f,t in nav)
 p.joinpath(file).write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Thirumoorthi Samiyappan</title><meta name="description" content="Thirumoorthi Samiyappan — AI, data science and technical architecture. Explore projects, learning resources and qualifications."><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css?v=20260924-pages2"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/index.html"><b class="mark">ts</b><span>Thirumoorthi S.<small>AI & ENGINEERING</small></span></a><nav aria-label="Main navigation">{n}</nav><a class="github" href="/projects.html">View Projects</a></header><main id="main">{body}</main><footer><a class="brand" href="/index.html"><b class="mark">ts</b><span>Ideas into working systems.</span></a><span>Chennai, India <i> / </i> © 2026 Thirumoorthi S.</span><a href="/projects.html">View projects ↗</a></footer><script src="/app.js?v=20260924-swing"></script></body></html>''')
page('index.html','About Me','''<section class="hero"><div class="hero-copy"><p class="eyebrow">TECHNICAL ARCHITECT · CHENNAI, INDIA</p><h1>Human insight.<br> Intelligent<br> <em>engineering.</em></h1><p class="intro">I'm Thirumoorthi Samiyappan. I connect business problems with AI, data, and software architecture to build systems that work in the real world.</p><div class="cta"><a class="button" href="/projects.html">Explore my work <span>↗</span></a><a class="textlink" href="/references.html">Inside my reference hub →</a></div></div><aside class="identity-panel"><div class="portrait-frame"><img src="/portrait.jpg" alt="Thirumoorthi Samiyappan" width="398" height="398"></div><div class="panel-bottom"><h2>Thirumoorthi<br>Samiyappan</h2><p>Generative AI · Data Science · Architecture</p></div></aside></section><div class="discipline"><span>PYTHON</span><span>GENERATIVE AI</span><span>RAG & EMBEDDINGS</span><span>CLOUD ARCHITECTURE</span><span>AGENTIC SYSTEMS</span></div><section class="about"><div><p class="eyebrow">01 — ABOUT ME</p><h2>Business context.<br>Engineering depth.</h2></div><div><p class="large">My work sits at the intersection of data science, enterprise operations, and applied AI.</p><p>My background spans automotive and telecom, with experience in supply chain, warehouse, and invoicing operations at HCL Technologies and Ford Motors. That grounding shapes how I approach architecture: start with the problem, understand the data, and make the solution practical.</p><p>I focus on retrieval-augmented generation, agentic workflows, Python services, and the engineering needed to move AI ideas into useful applications.</p></div></section><section class="focus-grid"><article><span class="num">01</span><h3>Applied intelligence</h3><p>LLM applications, retrieval, embeddings, and prompt engineering.</p></article><article><span class="num">02</span><h3>Systems that connect</h3><p>Python services, data pipelines, APIs, and cloud architecture.</p></article><article><span class="num">03</span><h3>Learning through building</h3><p>Experiments, implementation references, and reusable technical knowledge.</p></article></section>''')
projects=[('Census Income Prediction','Machine Learning','Census-Income-Prediction','An income prediction project, with the implementation available in the public repository.','Python · Classification','01'),('Time Series Models','Machine Learning','TimeSeries-Models','A collection of time series modeling work and forecasting examples.','Python · Forecasting','02'),('ML Deployment Test','Deployment','MLDeployTest','Machine learning deployment experiments connecting models with application delivery.','Machine learning · Deployment','03'),('Missing Values Graph','Data Analysis','MissingValuesGraph','A project exploring missing values and their visual representation.','Data analysis · Visualization','04'),('ML Model Samples','Machine Learning','ML_Model_Samples','Model examples for exploring machine learning implementation patterns.','Python · Model development','05')]
cards=''.join(f'''<article class="project" id="project-{num}" data-category="{cat}" data-title="{name}" data-order="{num}"><div class="project-art art{num}"><span>{cat.upper()}</span><b>{num}</b><span class="art-caption">{tech}</span></div><div class="project-body"><p class="eyebrow">PROJECT NOTEBOOK</p><h2>{name}</h2><p>{desc}</p><a href="/projects.html#project-{num}">Read project note <span>↗</span></a></div></article>''' for name,cat,repo,desc,tech,num in projects)
page('projects.html','Projects','''<section class="page-head"><p class="eyebrow">02 — SELECTED WORK</p><h1>Built to <em>learn.</em><br> Shared to build on.</h1><p>Experiments and implementations across machine learning, data, and deployment.</p></section><div class="toolbar"><div class="filters" aria-label="Project categories"><button class="active" data-filter="All" aria-pressed="true">All work</button><button data-filter="Machine Learning" aria-pressed="false">Machine learning</button><button data-filter="Data Analysis" aria-pressed="false">Data analysis</button><button data-filter="Deployment" aria-pressed="false">Deployment</button></div><div class="searchrow"><input id="search" type="search" aria-label="Search projects" placeholder="Search projects…"><select id="sort" aria-label="Sort projects"><option value="featured">Featured first</option><option value="az">Title A–Z</option></select><button id="layout" aria-pressed="false">List view</button></div></div><section class="project-grid">'''+cards+'''</section><p id="empty" hidden>No matching projects. Try a different search or category.</p>''')
refs=[('01','Generative AI','Generative-AI-Roadmap','A roadmap for exploring generative AI concepts and implementation.'),('02','Prompt engineering','Prompt_Engineering','Resources and examples for working with language model prompts.'),('03','AI & machine learning','AIML_Materials','A collection of AI and machine learning study materials.'),('04','Cloud architecture','AWS_Solution_Architect_SAA-C03','Study resources for AWS Solutions Architect topics.'),('05','Data science','data_science_study_material','Reference materials covering data science fundamentals and practice.'),('06','LLM applications','Maven---Build-LLM-Applications-from-scratch','Learning materials for building applications with large language models.')]
page('references.html','Reference Hub','''<section class="page-head"><p class="eyebrow">03 — THE REFERENCE HUB</p><h1>A curious mind.<br> An <em>open notebook.</em></h1><p>My curated collections of learning resources, examples, and technical references.</p></section><section class="reference-list">'''+''.join(f'<article class="reference"><span class="num">{n}</span><div><h2>{title}</h2><p>{desc}</p></div><span class="resource-type">LOCAL COLLECTION</span><span class="arrow" aria-hidden="true">✦</span></article>' for n,title,repo,desc in refs)+'''</section>''')
page('certifications.html','Certifications','''<section class="page-head"><p class="eyebrow">04 — CONTINUOUS LEARNING</p><h1>Knowledge is<br> a <em>work in progress.</em></h1><p>The formal learning behind my practice in AI and software engineering.</p></section><section class="credentials"><article class="credential"><div class="credential-symbol" aria-hidden="true">AI</div><div><p class="eyebrow">PROFESSIONAL EDUCATION</p><h2>Master’s Program in<br>Artificial Intelligence</h2><p>Simplilearn</p><span class="credential-label">Artificial intelligence & applied learning</span></div></article><article class="credential"><div class="credential-symbol second" aria-hidden="true">MCA</div><div><p class="eyebrow">ACADEMIC QUALIFICATION</p><h2>Master of Computer<br>Applications</h2><p>K. S. Rangasamy College of Technology</p><span class="credential-label">Computer applications & software foundations</span></div></article></section><aside class="cert-note"><span>i</span><p>Certificate documents and verification links have not been published here yet.</p></aside>''')
p.joinpath('favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#234ce6"/><text x="5" y="24" font-size="23" font-family="Arial" font-weight="bold" fill="#ffffff">ts</text></svg>')

# Independent exam preparation paths; exam facts transcribed into this site.
from html import escape
practice_routes={'Foundations':'/claude-architect-foundations-practice.html','Professional':'/claude-architect-professional-practice.html'}
exams=[
 {'slug':'claude-architect-foundations','level':'Foundations','code':'CCAR-F','questions':60,'summary':'Build your understanding of agent orchestration, tools, Claude Code, structured prompts, and reliable context handling.','domains':[
 ('Agentic Architecture & Orchestration',27,'Define the agent’s goal, available actions, and stopping conditions before adding autonomy. Separate model decisions from deterministic control logic. Treat retries, escalation, and human approval as explicit workflow steps.','Sketch a document-triage agent. Show how it handles missing information, a failed tool call, and a request that requires human approval.'),
 ('Tool Design & MCP Integration',18,'Make each tool’s purpose, inputs, and outputs unambiguous. Validate arguments and enforce permissions in the application. Distinguish tool execution failures from valid empty results so the agent can recover appropriately.','Write a contract for a read-only customer lookup tool, including required inputs, error responses, and the access checks performed before execution.'),
 ('Claude Code Configuration & Workflows',20,'Keep repository guidance specific to the project: build steps, conventions, test expectations, and boundaries. Review proposed changes and use the project’s checks before accepting them. Scope permissions to the work being performed.','Draft repository guidance for a small Python service. Include how to run tests, which files need extra review, and when the assistant should ask for clarification.'),
 ('Prompt Engineering & Structured Output',20,'State the task, constraints, source material, and expected output clearly. Treat retrieved content as data rather than trusted instructions. Validate structured responses against a schema and define what happens when information is missing.','Design a document-extraction prompt and output schema. Include a missing-value policy and test it with incomplete or contradictory input.'),
 ('Context Management & Reliability',15,'Select relevant context and preserve the source of important facts. Long histories need deliberate summarization, while retrieval needs relevance checks. Handle timeouts, malformed outputs, and insufficient evidence with explicit fallback behavior.','Create a recovery plan for an assistant that loses a source reference, receives conflicting documents, or reaches its context limit.') ]},
 {'slug':'claude-architect-professional','level':'Professional','code':'CCAR-P','questions':63,'summary':'Practice architecture trade-offs across enterprise integration, evaluation, governance, and production operations.','domains':[
 ('Solution Design & Architecture',17,'Begin with business outcomes and measurable constraints. Compare a deterministic workflow, a retrieval-assisted application, and an autonomous agent against the same requirements. Make ownership and failure boundaries visible in the design.','Compare two architectures for a service-request assistant using latency, cost, reliability, and approval requirements. Explain which trade-offs you would accept.'),
 ('Claude Models, Prompting & Context Engineering',13,'Choose models and context strategies using representative tasks and measured outcomes. Consider input quality, reasoning demands, latency, and cost together. A larger context window does not remove the need for relevance and evidence tracking.','Define an experiment comparing two model configurations on the same tasks. Specify quality criteria, latency measurements, and a cost budget.'),
 ('Integration',19,'Design interfaces around data ownership, authorization, and failure recovery. Separate read operations from consequential writes. Use appropriate validation, idempotency, and retry policies at service boundaries rather than relying on prompts alone.','Design a RAG assistant that reads internal documents and creates service tickets. Show where retrieval permissions, approval, and duplicate prevention apply.'),
 ('Evaluation, Testing & Optimization',16,'Build a representative evaluation set before optimizing. Break results down by task and failure type, and combine automated checks with human review where judgment matters. Re-test after changes to models, prompts, retrieval, or tools.','Create an evaluation matrix covering answer quality, groundedness, tool selection, latency, and cost. Define the evidence required to release a change.'),
 ('Governance, Safety & Risk Management',14,'Identify sensitive data, risky actions, and accountable owners. Enforce access, retention, and approval policies outside the model. Consider prompt injection and unintended disclosure in the context of actual data flows and permissions.','Threat-model an assistant that processes confidential documents. Define preventive controls, audit events, and escalation paths for the highest-impact failures.'),
 ('Stakeholder Communication & Lifecycle Management',14,'Translate technical results into business consequences and explicit decisions. Agree on acceptance criteria, operating responsibilities, and feedback loops. Plan for model changes, incidents, rollback, and retirement throughout the application lifecycle.','Write a release recommendation that includes measured benefits, unresolved risks, ownership, and rollback criteria for a business sponsor.'),
 ('Developer Productivity & Operational Enablement',7,'Give teams reusable patterns, useful observability, and clear operating guidance. Standardize common practices while preserving project-specific checks. Measure whether the tooling helps teams deliver reliable results rather than only increasing generated output.','Draft an operating checklist covering run traces, tool failures, cost trends, incident response, and how teams share improvements.') ]}
]

# The source guide exposes 30 task statements across the five Foundations domains.
# Keep the task names and source lesson URLs visible so this page works as a study map,
# not just a high-level summary.
foundation_tasks=[
 ('Agentic Architecture & Orchestration',27,'Design and implement agentic systems using Claude’s API, including loop management, orchestration patterns, guardrails, and the Claude Agent SDK.',[
  ('1.1 Agentic Loops','agentic-architecture/1-1-agentic-loops','Use stop_reason as the deterministic loop signal: continue on tool_use and finish on end_turn. Append tool results to the conversation before the next request.'),
  ('1.2 Multi-Agent Orchestration','agentic-architecture/1-2-orchestration-patterns','Use hub-and-spoke coordination for the exam: the coordinator decomposes work, routes context, aggregates results, and keeps subagents from communicating directly.'),
  ('1.3 Subagent Invocation & Context Passing','agentic-architecture/1-3-subagent-invocation-context','Give the coordinator Task/Agent permission, pass context explicitly, and preserve structured metadata such as source URLs and document names.'),
  ('1.4 Workflow Enforcement & Handoff','agentic-architecture/1-4-workflow-enforcement-handoff','Use programmatic gates for money, security, and compliance; prompts are probabilistic, while prerequisite checks and hooks are deterministic.'),
  ('1.5 Agent SDK Hooks','agentic-architecture/1-5-agent-sdk-hooks','Use PreToolUse to block or rewrite a call before execution and PostToolUse to normalise results after execution.'),
  ('1.6 Task Decomposition Strategies','agentic-architecture/1-6-task-decomposition','Match fixed sequential pipelines to predictable work and dynamic decomposition to open-ended investigation; watch for narrow decomposition and attention dilution.'),
  ('1.7 Session State & Resumption','agentic-architecture/1-7-session-state-resumption','Resume when context is still valid, fork for a divergent approach, and start fresh with a structured summary when the old context is stale.') ]),
 ('Tool Design & MCP Integration',18,'Design effective tool schemas, implement MCP servers and clients, and integrate external services into Claude-powered applications.',[
  ('2.1 Tool Interface Design','tool-design-mcp/2-1-tool-schema-design','Descriptions should state purpose, inputs, examples, edge cases, and boundaries. Sharpen descriptions before adding a routing layer.'),
  ('2.2 Structured Error Responses','tool-design-mcp/2-2-structured-error-responses','Return structured errorCategory, isRetryable, and description metadata. Separate access failures from valid empty results; retry transient failures, not business or permission failures.'),
  ('2.3 Tool Distribution & Tool Choice','tool-design-mcp/2-3-tool-distribution-choice','Keep agents near four or five role-specific tools, consolidate same-shaped operations, and use auto, any, or forced tool selection for the right guarantee.'),
  ('2.4 MCP Server Integration','tool-design-mcp/2-4-mcp-server-integration','Use project .mcp.json for shared configuration, user-level settings for personal connections, environment variables for secrets, and community servers for standard integrations.'),
  ('2.5 Built-in Tools','tool-design-mcp/2-5-built-in-tools','Remember the Claude Code tools: Read, Write, Edit, Bash, Grep, and Glob. Grep searches file contents; Glob matches file paths.') ]),
 ('Claude Code Configuration & Workflows',20,'Configure Claude Code for development workflows, manage settings, hooks, permissions, and integrate with CI/CD pipelines.',[
  ('3.1 CLAUDE.md Hierarchy, Scoping & Modular Organisation','claude-code-config/3-1-claude-md-hierarchy','Project instructions are shared through git; user instructions are personal. CLAUDE.md files are guidance, not deterministic enforcement.'),
  ('3.2 Custom Slash Commands & Skills','claude-code-config/3-2-slash-commands-skills','Use project .claude/skills or .claude/commands for shared workflows; user-level folders are personal. Skills are directories containing SKILL.md.'),
  ('3.3 Path-Specific Rules','claude-code-config/3-3-path-specific-rules','Use path-scoped rules for conventions that should load only for matching files; this keeps irrelevant context out of a session.'),
  ('3.4 Plan Mode vs Direct Execution','claude-code-config/3-4-plan-mode-execution','Use direct execution for clear, limited changes and plan mode for ambiguous work spanning decisions or modules.'),
  ('3.5 Iterative Refinement Techniques','claude-code-config/3-5-iterative-refinement','Use concrete examples when the desired transformation is known, interview first in unfamiliar domains, and batch feedback when changes interact.'),
  ('3.6 CI/CD Integration','claude-code-config/3-6-cicd-integration','Use -p/--print for non-interactive CI runs and machine-readable output options when downstream automation consumes the result.') ]),
 ('Prompt Engineering & Structured Output',20,'Craft effective prompts, implement structured output patterns, and apply production prompt-engineering techniques.',[
  ('4.1 System Prompts with Explicit Criteria','prompt-engineering/4-1-system-prompts','Replace vague confidence language with explicit categories, boundaries, and concrete examples; temporarily disable high-false-positive categories while refining them.'),
  ('4.2 Few-Shot Prompting','prompt-engineering/4-2-few-shot-prompting','Use representative input/output examples when detailed instructions still produce inconsistent formats, judgements, or extraction fields.'),
  ('4.3 Structured Output with Tool Use','prompt-engineering/4-3-structured-output','Schemas prevent syntax errors but not semantic errors. Use nullable fields for genuinely missing data and tool_choice any when a tool call is required.'),
  ('4.4 Validation, Retry & Feedback Loops','prompt-engineering/4-4-validation-retry-loops','Retry with the original source, failed output, and specific validation error; do not retry when the source cannot contain the missing information.'),
  ('4.5 Batch Processing Strategies','prompt-engineering/4-5-batch-processing','Refine prompts on a representative sample before batch submission. Batch is cost-efficient but latency-tolerant; tool loops remain synchronous.'),
  ('4.6 Multi-Instance & Multi-Pass Review','prompt-engineering/4-6-multi-pass-review','Use independent review instances, per-file passes, integration review, and calibrated confidence routing instead of trusting the generator to review itself.') ]),
 ('Context Management & Reliability',15,'Manage context windows effectively, implement caching strategies, handle long conversations, and build reliable production systems.',[
  ('5.1 Context Window Management','context-management/5-1-context-window-management','Protect transactional facts in a persistent case-facts block, put key findings first, trim tool results, and place stable prefixes before cache breakpoints.'),
  ('5.2 Escalation & Ambiguity Resolution','context-management/5-2-escalation-ambiguity','Escalate on an explicit human request, a policy gap, or inability to progress; do not use sentiment or raw self-reported confidence as the trigger.'),
  ('5.3 Error Propagation in Multi-Agent Systems','context-management/5-3-error-propagation','Recover transient failures locally, propagate structured failure context and partial results, and never hide a timeout as an empty success.'),
  ('5.4 Codebase Exploration & Context Degradation','context-management/5-4-codebase-exploration','Explore incrementally, delegate verbose discovery to isolate context, and persist key findings in scratchpads or crash-recovery manifests.'),
  ('5.5 Human Review & Confidence Calibration','context-management/5-5-human-review-calibration','Measure accuracy by document type and field segment, calibrate confidence on labelled data, and use stratified sampling before reducing human review.'),
  ('5.6 Information Provenance & Multi-Source Synthesis','context-management/5-6-information-provenance','Preserve claim, source URL, document, excerpt, and date. Annotate conflicts instead of selecting a value arbitrarily.') ])]
exams[0]['guide_summary']='The guide maps 30 task statements to five domains. Use the weight as a study-time signal, then work through each linked lesson and exercise.'
exams[0]['domains']=[(name,weight,summary,'Complete the linked lesson, write a small implementation or decision record, and explain the exam trap in your own words.',tasks) for name,weight,summary,tasks in foundation_tasks]
def exam_buttons(e):
 return f'<div class="exam-actions"><a class="button" href="/{e["slug"]}.html">Learn & prepare <span aria-hidden="true">→</span></a><a class="button button-secondary" href="{practice_routes[e["level"]]}" aria-label="Start local Practice Exam for {e["level"]}">Start Practice Exam <span aria-hidden="true">↗</span></a></div>'
examcards=''
for e in exams:
 examcards+=f'''<article class="exam-card"><div class="exam-top"><span class="path-label">PREPARATION PATH</span><span class="exam-code">{e['code']}</span></div><h2>Claude Certified Architect <span>— {e['level']}</span></h2><p>{e['summary']}</p>{f'<p class="guide-summary">{e["guide_summary"]}</p>' if e.get('guide_summary') else ''}<ul class="exam-facts"><li><strong>{e['questions']}</strong> exam questions</li><li><strong>120</strong> minutes</li><li><strong>{len(e['domains'])}</strong> topic areas</li></ul>{exam_buttons(e)}<p class="exam-hint">Practice opens in this portfolio with a focused, local question set.</p></article>'''
old=p.joinpath('certifications.html').read_text()
a=old.index('<section class="credentials">');b=old.index('</section>',a)+len('</section>')
education=old[a:b]
page('certifications.html','Certifications',f'''<section class="page-head"><p class="eyebrow">04 — CONTINUOUS LEARNING</p><h1>Build your knowledge.<br> <em>Test your judgment.</em></h1><p>Prepare for Claude architecture topics, then put your understanding into practice.</p></section><section class="exam-grid" aria-label="Claude certification preparation">{examcards}</section><p class="source-note">The exam facts, topic weights, and lesson notes on these pages have been transcribed into this portfolio as a self-contained study resource. These are study paths, not credentials earned or official exam registrations.</p><section class="education-heading"><p class="eyebrow">MY LEARNING BACKGROUND</p><h2>Education & professional learning</h2></section>{education}<aside class="cert-note"><span>i</span><p>Certificate documents and verification links have not been published here yet.</p></aside>''')
for e in exams:
 topics=''
 for i,domain in enumerate(e['domains'],1):
  name,weight,lesson,exercise,*extra=domain
  tasks=extra[0] if extra else []
  task_markup=''
  if tasks:
   task_markup='<div class="task-list"><h3>Lesson map</h3>'+''.join(f'<details class="task-item"><summary><span>{escape(title)}</span><b>Study note</b></summary><small>{escape(detail)}</small></details>' for title,path,detail in tasks)+'</div>'
  topics+=f'''<article class="study-topic" id="topic-{i}"><div class="topic-heading"><span class="num">{i:02}</span><h2>{escape(name)}</h2><span class="topic-weight">{weight}%</span></div><div class="weight-track" aria-hidden="true"><span style="width:{weight}%"></span></div><p>{lesson}</p>{task_markup}<div class="try-it"><h3>Study action</h3><p>{exercise}</p></div></article>'''
 contents=''.join(f'<a href="#topic-{i}">{escape(d[0])} <span>{d[1]}%</span></a>' for i,d in enumerate(e['domains'],1))
 exam_details='''<p>The exam format captured here is 60 questions in 120 minutes, with a $125 USD fee, a 720/1000 pass mark, and 12-month credential validity. Delivery is described as online proctoring or a test centre.</p>''' if e['level']=='Foundations' else '''<p>This portfolio’s Professional path is an architecture practice guide covering seven competency areas. Use the local question set to rehearse trade-offs, then verify any official booking details separately.</p>'''
 page(e['slug']+'.html',f'Claude Architect {e["level"]} — Preparation',f'''<section class="page-head prep-head"><a class="back-link" href="/certifications.html">← All certification paths</a><p class="eyebrow">CLAUDE CERTIFIED ARCHITECT · {e['code']}</p><h1>{e['level']}.<br> <em>Learn with intent.</em></h1><p>{e['summary']}</p></section><div class="prep-layout"><aside class="study-sidebar"><p class="eyebrow">YOUR STUDY MAP</p><nav aria-label="Study topics">{contents}</nav><a class="button" href="{practice_routes[e['level']]}">Start Practice Exam ↗</a><p>Practice is built into this portfolio as a local question set.</p></aside><div class="study-content"><section class="study-overview"><h2>Know the exam path</h2><ul class="exam-facts"><li><strong>{e['questions']}</strong> questions</li><li><strong>120</strong> minutes</li><li><strong>5</strong> domains</li></ul>{exam_details}<p>Use the local practice page for short, domain-based rounds with immediate feedback.</p><p>A 72% readiness target is a useful study signal, not a verified official passing score.</p></section><section class="study-method"><h2>A practical way to prepare</h2><ol><li>Work through each lesson note and write the decision rule, anti-pattern, and implementation detail in your own words.</li><li>Complete the study action for each domain. Record assumptions, trade-offs, and failure handling.</li><li>Use the local practice round to identify gaps before a timed attempt.</li><li>Review missed questions by domain, revisit the reasoning, and try again.</li></ol></section>{topics}<section class="study-finish"><p class="eyebrow">READY TO APPLY IT?</p><h2>Make the next attempt count.</h2><p>Open the local practice set for Architect {e['level']}.</p><a class="button" href="{practice_routes[e['level']]}">Start Practice Exam ↗</a></section><p class="source-note">Lesson titles, task statements, weights, and study details have been transcribed into this self-contained portfolio page. This is supplementary study guidance, not an official certification registration or credential.</p></div></div>''')
# Keep the Certifications navigation active on the nested preparation pages.
for e in exams:
 f=p.joinpath(e['slug']+'.html');s=f.read_text().replace('<a href="/certifications.html" >','<a href="/certifications.html" aria-current="page">');f.write_text(s)

# Small, self-contained practice rounds keep the certification buttons useful
# without sending visitors to another site.
practice_sets={
 'Foundations':[
  ('Agentic loops','An agent receives a tool_use stop reason. What should the application do next?',['End the session immediately','Append the tool result and request the next model turn','Ask the user to restart','Ignore the tool call'],'b','The loop continues after tool_use; the tool result becomes the next conversation turn.'),
  ('Tool design','A tool is often mis-selected by the model. What is the best first fix?',['Add a second routing agent','Sharpen the tool description, examples, and boundaries','Increase the temperature','Hide the tool from the model'],'b','Clear purpose, inputs, examples, and boundaries usually improve routing before extra orchestration.'),
  ('Claude Code workflows','Where should shared repository instructions live?',['A private chat message','A personal desktop note','A project-level CLAUDE.md committed with the repository','Only in the CI provider'],'c','Project-level guidance is shareable and versioned with the codebase.'),
  ('Structured output','Extraction fields are inconsistent even though the schema is valid. What should you add?',['Representative few-shot examples','A longer system greeting','More random sampling','A second unrelated tool'],'a','Examples show the intended format and judgment more concretely than prose alone.'),
  ('Context reliability','A long case summary risks losing the refund amount. What protects it best?',['Keep every raw tool response forever','Put key transactional facts in a persistent case-facts block','Ask the model to remember it','Increase temperature'],'b','A compact, explicit facts block preserves high-value details through summarisation.')
 ],
 'Professional':[
  ('Architecture','A service-request assistant can use a workflow, RAG, or an autonomous agent. What should guide the choice?',['The newest model name','Business outcomes, risk, latency, and ownership constraints','The longest prompt','The most autonomous option'],'b','Choose the least complex architecture that meets measured business and risk requirements.'),
  ('Context engineering','How should two model configurations be compared?',['Use one anecdotal prompt','Run representative tasks with quality, latency, and cost measures','Pick the larger context window','Compare marketing claims'],'b','A fair evaluation uses the same representative tasks and explicit success measures.'),
  ('Integration','A RAG assistant can create service tickets. Where should approval happen?',['Only in the prompt','At the service boundary before the consequential write','After the ticket is created','Never'],'b','Authorization and approval belong in deterministic application controls around writes.'),
  ('Evaluation','What belongs in a release evaluation matrix?',['Only average answer length','Quality, groundedness, tool selection, latency, and cost','Only a human thumbs-up','Only token count'],'b','Break results down by task and failure type, using both automated and human checks where needed.'),
  ('Governance','What is the strongest control for confidential documents?',['Trust the model not to disclose them','Enforce access and retention outside the model and audit events','Remove all logging','Use a more cheerful prompt'],'b','Policies must be enforced in the surrounding system, with accountable audit trails.')
 ]
}
for level, questions in practice_sets.items():
 items=[]
 for i,(topic,question,options,answer,explanation) in enumerate(questions,1):
  labels=''.join(f'<label><input type="radio" name="q{i}" value="{chr(97+j)}"> <span>{escape(option)}</span></label>' for j,option in enumerate(options))
  items.append(f'<article class="practice-question" data-answer="{answer}"><p class="eyebrow">ROUND {i:02} · {escape(topic)}</p><h2>{escape(question)}</h2><div class="practice-options">{labels}</div><button class="button practice-check" type="button">Check answer</button><p class="practice-result" role="status" aria-live="polite"></p><p class="practice-explanation">{escape(explanation)}</p></article>')
 page_name=f'claude-architect-{level.lower()}-practice.html'
 page(page_name,f'Claude Architect {level} — Practice',f'''<section class="page-head prep-head"><a class="back-link" href="/certifications.html">← All certification paths</a><p class="eyebrow">LOCAL PRACTICE ROUND · CCAR-{('F' if level=='Foundations' else 'P')}</p><h1>Practice {level}.<br> <em>Think it through.</em></h1><p>Five focused questions built from the study map. Choose an answer, check your reasoning, and use the explanation to guide your next review.</p></section><section class="practice-shell"><div class="practice-banner"><strong>Self-contained study set</strong><span>No account, timer, or external link required.</span></div>{''.join(items)}<div class="study-finish"><p class="eyebrow">KEEP GOING</p><h2>Review the full study map.</h2><p>Return to the {level} preparation path for every domain, task statement, and study action.</p><a class="button" href="/{'claude-architect-foundations' if level=='Foundations' else 'claude-architect-professional'}.html">Back to Learn & prepare ↗</a></div></section>''')

# Keep the Certifications navigation active on the nested preparation pages.
for e in exams:
 for suffix in ('', '-practice'):
  f=p.joinpath(e['slug']+suffix+'.html')
  if f.exists():
   s=f.read_text().replace('<a href="/certifications.html" >','<a href="/certifications.html" aria-current="page">')
   f.write_text(s)

